build_docker_image:
  stage: build
  image: docker:20.10.13
  script:
    - docker build -t website .

test_with_pytest:
        stage: test
        script:
                - apt-get update -qy
                - apt-get install -y python3-pip
                - pip install -r requirements.txt
                - pytest --verbose --color=yes
