version: "3.8"
services:
  web:
    build: ./flask-example
    container_name: flask
    volumes:
      - ./app/:/code
    networks:
      customnetwork:
        ipv4_address: 172.15.0.3
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 88:80
    depends_on:
      - web
    networks:
      customnetwork:
        ipv4_address: 172.15.0.4
  dns:
    build: ./dns
    container_name: bind9
    ports:
      - 53:53
    networks:
      customnetwork:
        ipv4_address: 172.15.0.2

networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.15.0.0/16